### ISSUE TITLE
podop raise exception on `username@[ip]` address

### ISSUE THREAD

**Issue by bclermont** [Mailu/Podop#7]
Using 1.8 master docker images in kubernetes.

Testing if it's an openrelay with http://www.aupads.org/test-relay.html and whenever the address is in format `username@[ip]` it raise exception:

```
Feb 03 10:25:36 mail postfix/smtpd[281512]: warning: socketmap:unix:/tmp/podop.socket:senderaccess socketmap server temporary error: unknown error
Feb 03 10:25:36 mail postfix/smtpd[281512]: warning: socketmap:unix:/tmp/podop.socket:senderaccess lookup error for "spamtest@[x.y.z.w]"
Feb 03 10:25:36 mail postfix/smtpd[281512]: NOQUEUE: reject: RCPT from santuario.pads.ufrj.br[146.164.48.5]: 451 4.3.5 <spamtest@[206.189.154.202]>: Sender address rejected: Server configuration error; from=<spamtest@[x.y.z.w]> to=<relaytest%antispam-ufrj.pads.ufrj.br@> proto=SMTP helo=<antispam-ufrj.pads.ufrj.br>
ERROR:root:Error when processing request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/podop/postfix.py", line 104, in process_request
    result = await table.get(key)
  File "/usr/lib/python3.8/site-packages/podop/table.py", line 35, in get
    raise Exception(request.status)
Exception: 500
```

**Comment by ghostwheel42** [comment]
Hi. Podop catched an error from the (mailu) backend and is just logging the "500 internal server error" here.
The log is not pretty and it looks like the python exception was not catched, but it was and a 4XX temporary failure was returned. The error has to be fixed in the mailu backend.
Alex
