### ISSUE TITLE
Error 500 on alias lookup.

### ISSUE THREAD

**Issue by GuardMoony** [Mailu/Podop#8]
Version: 1.8
Custom setup with traefik proxy

It seems i'm getting a http 500 error on the alias lookup. This while the same e-mail can be used to login in the admin interface. 
This ofcoarse causes all mail delivery to fail towards this account. The database for alias is also empty.

```
Mar 02 20:51:01 mail postfix/smtpd[2471]: connect from containers_traefik.1.ohh2lccbu7fs69j7c5ya48q12.containers[10.0.1.171]
ERROR:root:Error when processing request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/podop/postfix.py", line 104, in process_request
    result = await table.get(key)
  File "/usr/lib/python3.8/site-packages/podop/table.py", line 35, in get
    raise Exception(request.status)
Exception: 500
Mar 02 20:51:01 mail postfix/smtpd[2471]: warning: socketmap:unix:/tmp/podop.socket:alias socketmap server temporary error: unknown error
Mar 02 20:51:01 mail postfix/smtpd[2471]: warning: socketmap:unix:/tmp/podop.socket:alias lookup error for "valentijn@xxx.xx"
Mar 02 20:51:01 mail postfix/smtpd[2471]: NOQUEUE: reject: RCPT from containers_traefik.1.ohh2lccbu7fs69j7c5ya48q12.containers[10.0.1.171]: 451 4.3.0 <valentijn@xxx.xx>: Temporary lookup failure; from=<moonl1ght@yyy.yy> to=<valentijn@xxx.xx> proto=ESMTP helo=<leibniz.yyy.yy>
Mar 02 20:51:01 mail postfix/smtpd[2471]: disconnect from containers_traefik.1.ohh2lccbu7fs69j7c5ya48q12.containers[10.0.1.171] ehlo=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=4/6
```

```
# The alias map actually returns both aliases and local mailboxes, which is
# required for reject_unlisted_sender to work properly 
virtual_alias_domains =                                                                                                                                                                                          
virtual_alias_maps = ${podop}alias                                                                                                                                                                                
virtual_mailbox_domains = ${podop}domain                                                                                                                                                                          
virtual_mailbox_maps = ${podop}mailbox

**Comment by GuardMoony** [comment]
Temp workarround (Disables aliases):
override virtual_alias_maps

Also tested adding a alias so the db isn't empty. But this still resulted in error 500

**Comment by GuardMoony** [comment]
Ok, think i found the issue. My RECIPIENT_DELIMITER envvar was not set. Maybe at a safeguard/default?

**Comment by ghostwheel42** [comment]
RECIPIENT_DELIMITER defaults to "+" in Mailu for quite some time now.
